### ISSUE TITLE
Apache2 Directives

### ISSUE THREAD

**Issue by rchampagneca** [MoriTanosuke/wallabag-docker#1]
My Apache2 directives for /var/www are:

AllowOverride None
Order Allow,Deny
Allow from All

I'm getting the following log entry:

`wallabag_1  | [Sun Nov 06 20:53:08.030807 2016] [autoindex:error] [pid 9] [client XX.XXX.XXX.XX:45101] AH01276: Cannot serve directory /var/www/html/: No matching DirectoryIndex (index.php,index.html) found, and server-generated directory index forbidden by Options directive`

**Comment by MoriTanosuke** [comment]
Try opening _/app.php_ instead of _/_. Does this work?

I also just pushed a commit with an example _docker-compose.yml_, if you want to give that a try.

**Comment by rchampagneca** [comment]
As you may have guessed, I'm quite a **newbie** with regards to Docker.

So, I've pulled the latest **Dockerfile** and **Docker-Compose YML**  files. I'm getting:

`Fatal error: Uncaught PDOException: SQLSTATE[HY000] [14] unable to open database file in /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43 Stack trace: #0 /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(43): PDO->__construct('sqlite:/var/www...', 'root', NULL, Array) #1 /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOSqlite/Driver.php(56): Doctrine\DBAL\Driver\PDOConnection->__construct('sqlite:/var/www...', 'root', NULL, Array) #2 /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOSqlite\Driver->connect(Array, 'root', NULL, Array) #3 /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1017): Doctrine\DBAL\Connection->connect() #4 /var/www/wallabag/vendor/lexik/maintenance-bundle/Drivers/Query/DefaultQuery.php(52): Doctrine\DBAL\Connection->exec('CREATE TABLE IF...') #5 /var/www/wallabag/vendor/lexik/maintenance-bundle/Drivers/Query/DefaultQuery.php(38): Lexik\Bundl in /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php on line 82`

**Comment by MoriTanosuke** [comment]
Ah, I totally forgot that I ran the container with data from a previous backup. I added the empty _sqlite_ database to the repository, so if you run `docker-compose up` again, everything should be fine.

Please note, that the first login fails for some reason. If you re-open http://localhost:8111 you should see the default list of articles though. I don't know yet why the first login fails, but I always had some issues with wallabags URL redirection... :-(

**Comment by rchampagneca** [comment]
Making progress ... 
Got to the login screen, but during registration, I got **500: Internal Server Error**

`an exception occurred while executing 'INSERT INTO "wallabag_user" (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, locked, expired, expires_at, confirmation_token, password_requested_at, roles, credentials_expired, credentials_expire_at, name, created_at,`
`SQLSTATE[HY000]: General error: 8 attempt to write a readonly database`

**Comment by rchampagneca** [comment]
Ah! I had the wrong permissions on the data directory. 
Now, how can I identify to Wallabag my email server ?

**Comment by MoriTanosuke** [comment]
Ah, I was about to write about the permissions of the mounted _data_ directory. Glad you found it already.

This is more a question of configuring wallabag. Looks like the framework Symfony has a built in way to configure SMTP settings and the like, see https://github.com/wallabag/wallabag/pull/1824

For the Dockerfile, you can add a _parameters.yml_ like I [prepared in the _docker-compose.yml_](https://github.com/MoriTanosuke/wallabag-docker/blob/master/docker-compose.yml#L9). To get the current _parameters.yml_, start the container and execute the following command

```
docker cp wallabagdocker_wallabag_1:/var/www/wallabag/app/config/parameters.yml
```

If you renamed the directory with the _Dockerfile_ from _wallbag-docker_ to something else, you might want to check the name of the container first. Use

```
docker ps
```

to check the name of the running container and replace it in the command line above. After you copied the default _parameters.yml_ from your container, you can modify the file, enable the line in _docker-compose.yml_ and remove+restart the container.

To remove+restart, use

```
docker-compose stop
docker-compose rm
docker-compose up
```

HTH

**Comment by rchampagneca** [comment]
Hi, Just completed the installation as you've outlined in your posts above. Regards. Roger.
