### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by starsareintherose** [MoriTanosuke/wallabag-docker#3]
debconf: delaying package configuration, since apt-utils is not installed

error: /usr/src/php/ext/mcrypt does not exist

usage: /usr/local/bin/docker-php-ext-install [-jN] [--ini-name file.ini] ext-name [ext-name ...]
   ie: /usr/local/bin/docker-php-ext-install gd mysqli
       /usr/local/bin/docker-php-ext-install pdo pdo_mysql
       /usr/local/bin/docker-php-ext-install -j5 gd mbstring mysqli pdo pdo_mysql shmop

if custom ./configure arguments are necessary, see docker-php-ext-configure

Possible values for ext-name:
bcmath bz2 calendar ctype curl dba dom enchant exif ffi fileinfo filter ftp gd gettext gmp hash iconv imap intl json ldap mbstring mysqli oci8 odbc opcache pcntl pdo pdo_dblib pdo_firebird pdo_mysql pdo_oci pdo_odbc pdo_pgsql pdo_sqlite pgsql phar posix pspell readline reflection session shmop simplexml snmp soap sockets sodium spl standard sysvmsg sysvsem sysvshm tidy tokenizer xml xmlreader xmlwriter xsl zend_test zip

Some of the above modules are already compiled into PHP; please check
the output of "php -i" to see which modules are already loaded.
ERROR: Service 'wallabag' failed to build: The command '/bin/sh -c apt-get update && apt-get install -y         git         zip unzip         libfreetype6-dev         libjpeg62-turbo-dev         libmcrypt-dev         libpng-dev         && docker-php-ext-install -j$(nproc) iconv mcrypt         && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/         && docker-php-ext-install -j$(nproc) gd         && docker-php-ext-install bcmath' returned a non-zero code: 1

**Comment by MoriTanosuke** [comment]
@starsareintherose can you provide a description what you are trying to do?

**Comment by starsareintherose** [comment]
I'm trying to install wallabag, I try many methods and sources, all are failed. I change your dockerfile L14 "libpng12-dev \" to " libpng-dev" due to an error report. And then it reports the error and stops the installation.
And could I ask you another question?
Now I successfully install it via wallabag/docker, but it does not work, when I visit the domain, it redirects to my domain/login (SSL forced), but I can't visit it and just see "HTTP error 500", have you faced similar problems? Nginx setting may be the key, I guess.

**Comment by MoriTanosuke** [comment]
This image does not use nginx. Configuration of wallabag is problematic, especially if you are using a reverse proxy. I don't use the software anymore myself, because it was too much work to make it work with my setup.

The build error above is due to a change in the PHP setup. I'll fix the Dockerfile to prevent this error in the future and pin the PHP version so the image itself will build. All user configuration is out of scope for this project, sorry.

**Comment by starsareintherose** [comment]
OK, thanks, I hope it can work. In the future I can use it. Actually, after it reports `/usr/src/php/ext/mcrypt does not exist`, I build a dir like this, but it doesn't work.

**Comment by MoriTanosuke** [comment]
Yes, that's because PHP 7.x changed the install method for mcrypt. I will push a fix in a couple minutes for PHP8.

**Comment by starsareintherose** [comment]
Thanks, I'm using php 7.4

**Comment by MoriTanosuke** [comment]
Dockerfile is fixed in commit https://github.com/MoriTanosuke/wallabag-docker/commit/b674159b7383f97bbac6a815b208b17c11d52d46
